name: Deploy to DEV

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  actions: write

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fake deploy to DEV
        run: echo "Simulating DEV deployment for POC..."
      - name: Trigger DEV automation tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: VishalGiram0842/SampleRepoForCICD
          event-type: run-dev-tests
          client-payload: |
            { "source_repo": "${{ github.repository }}", "env": "DEV" }
